// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreServices.Api.ShoppingCart.Persitence;

#nullable disable

namespace StoreServices.Api.ShoppingCart.Migrations
{
    [DbContext(typeof(CartContext))]
    [Migration("20220510233528_MigrationMySqlInitial")]
    partial class MigrationMySqlInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("StoreServices.Api.ShoppingCart.Model.CartSession", b =>
                {
                    b.Property<int>("CartSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CartSessionId");

                    b.ToTable("CartSession");
                });

            modelBuilder.Entity("StoreServices.Api.ShoppingCart.Model.CartSessionDetail", b =>
                {
                    b.Property<int>("CartSessionDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CartSessionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProductSelected")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CartSessionDetailId");

                    b.HasIndex("CartSessionId");

                    b.ToTable("CartSessonDetail");
                });

            modelBuilder.Entity("StoreServices.Api.ShoppingCart.Model.CartSessionDetail", b =>
                {
                    b.HasOne("StoreServices.Api.ShoppingCart.Model.CartSession", "CartSession")
                        .WithMany("ListDetail")
                        .HasForeignKey("CartSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CartSession");
                });

            modelBuilder.Entity("StoreServices.Api.ShoppingCart.Model.CartSession", b =>
                {
                    b.Navigation("ListDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
